# Versione del file di configurazione
apiVersion: v2

metadata:
  projectName: "WebServer-UAT-Secure"
  description: "Ambiente di test per il nuovo web server aziendale con SSL."
  owner: "team.architects@mycompany.com"

environment:
  provider: "virsh"

# Elenco dei nodi (VM) da creare
nodes:
  - name: "web-server-01"
    os:
      distribution: "Rocky Linux"
      version: "9"
      # URL da cui scaricare l'immagine ISO per l'installazione.
      iso_url: "https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.4-x86_64-minimal.iso"
    resources:
      cpu: 2
      memory_mb: 2048
      disk_gb: 20
    network:
      ip: "192.168.100.50"
      gateway: "192.168.100.1"

provisioning:
  tool: "ansible"
  # Un array strutturato per i componenti software.
  software_components:
    - name: "nginx"
      version: "latest" # o una versione specifica come "1.24.0"
      source: "official_repo" # In futuro: "custom_repo", "epel", etc.
      # Campo libero dove l'utente descrive l'intent della configurazione.
      # Qui l'AI dovrà interpretare e generare i task Ansible corretti.
      configuration_details: |
        - Enable SSL/TLS using a self-signed certificate.
        - The certificate common name must be 'test.my-web-server.com'.
        - Create a virtual host that listens on port 443.
        - The document root should be '/var/www/html/secure'.
        - Add a basic index.html file to the document root.

    - name: "firewalld"
      version: "latest"
      source: "official_repo"
      configuration_details: |
        - Ensure the firewalld service is running.
        - Open port 443 for HTTPS traffic.
        - Open port 22 for SSH traffic.
        - Make the rules permanent.

    - name: "sudo"
      version: "latest"
      source: "official_repo"
      configuration_details: |
        - Create a user named 'devadmin'.
        - Add the 'devadmin' user to the 'wheel' group to grant sudo privileges.
