# ATLAS VM Configuration Examples
# This file shows different ways to specify software versions

# Example 1: Basic configuration with latest versions (default)
web_server_basic:
  hostname: "web-server-01"
  cpu: 4
  memory: 8192
  disk: 100
  os: "ubuntu-22.04"
  software:
    - nginx              # Will use latest available version
    - docker             # Will use latest available version  
    - monitoring-agent   # Will use latest available version

# Example 2: Mixed version specifications
web_server_mixed:
  hostname: "web-server-02"
  cpu: 4
  memory: 8192
  disk: 100
  os: "ubuntu-22.04"
  software:
    - name: nginx
      version: "1.20.2"          # Specific version
    - name: docker
      version: "latest"          # Explicit latest
    - name: nodejs
      version: "~18.0"           # Version range (18.x)
    - name: monitoring-agent     # No version = latest

# Example 3: Advanced configuration with sources and config
database_server:
  hostname: "db-server-01"  
  cpu: 8
  memory: 16384
  disk: 500
  os: "ubuntu-22.04"
  software:
    - name: postgresql
      version: "14.9"            # Specific version
      source: apt
      config:
        port: 5432
        max_connections: 200
        shared_buffers: "4GB"
    - name: backup-tools
      version: "stable"          # Stable version
    - name: monitoring-agent
      # No version specified = latest

# Example 4: Development environment with specific tool versions
dev_environment:
  hostname: "dev-server-01"
  cpu: 4
  memory: 8192
  disk: 200
  os: "ubuntu-22.04"
  software:
    - name: python
      version: "3.11"
    - name: nodejs
      version: "18.17.0"         # Exact version for consistency
      source: snap
    - name: docker
      version: "^24.0"           # Version range (24.x, compatible)
    - name: git
      # Latest version
    - name: vim
      # Latest version
    - name: code-server
      version: "latest"
      config:
        port: 8080
        auth: password

# Example 5: Production environment with LTS versions
production_web:
  hostname: "prod-web-01"
  cpu: 8
  memory: 16384
  disk: 200
  os: "ubuntu-22.04"
  software:
    - name: nginx
      version: "1.22.1"          # Stable production version
      config:
        worker_processes: auto
        keepalive_timeout: 65
    - name: certbot
      version: "lts"             # LTS version for stability
    - name: fail2ban
      # Latest version for security
    - name: monitoring-agent
      version: "stable"

# Example 6: Microservices stack
microservices_node:
  hostname: "micro-node-01"
  cpu: 6
  memory: 12288
  disk: 150
  os: "ubuntu-22.04"  
  software:
    - name: docker
      version: "24.0.6"
    - name: docker-compose
      version: "^2.20"           # Compatible with 2.20+
    - name: nginx
      version: "1.24"            # Load balancer
      config:
        upstream_servers:
          - "app1:3000"
          - "app2:3000"
    - name: redis
      version: "7.0"             # Session store
    - name: prometheus-node-exporter
      # Latest monitoring agent
